name: news_ok
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  equatable: ^2.0.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  google_sign_in:
  chopper: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.4
  chopper_generator: ^4.0.2
  bloc_test: ^8.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
